DROP DATABASE IF EXISTS business_card;
CREATE DATABASE IF NOT EXISTS business_card ;
USE business_card;
CREATE TABLE user (
    id INT(20) NOT NULL AUTO_INCREMENT,
    openid VARCHAR(255) NOT NULL UNIQUE,
    session_key VARCHAR(255) NOT NULL,
    nick_name VARCHAR(255) DEFAULT NULL,
    avatar_url VARCHAR(255) DEFAULT NULL,
    mobile INT(20) DEFAULT NULL,
    address VARCHAR(255) DEFAULT NULL,
    createtime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    des VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id),
    UNIQUE INDEX (id),
    UNIQUE INDEX  (openid)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
